### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Oroton** [BlackScorp/webrpg#2]
Using MySQL there was a few errors like index length greater than 1000..
Changed
  `username` varchar(112) NOT NULL,
  `password` varchar(254) NOT NULL,
  `email` varchar(112) NOT NULL,

Username and Email to 112 to suit.

Also Receiving many errors that,

Parse error: syntax error, unexpected '[' in ipg.brcadmin/webrpg/source/functions.php on line 59

Parse error: syntax error, unexpected '[' in /hermes/bosnaweb17a/b633/ipg.brcadmin/webrpg/source/bootstrap.php on line 25
& each of the basic events..

**Comment by BlackScorp** [comment]
about your Parse error. Youre using an outdated PHP Version

since php 5.4 http://php.net/manual/en/language.types.array.php  you can use short array syntax.

as you can see here http://php.net/supported-versions.php even php 5.6 has no active development anymore just security fixes.

why is email 112? and username 112?  according to email RFC 5321 https://tools.ietf.org/html/rfc5321#section-4.5.3  

   The maximum total length of a reverse-path or forward-path is 256
   octets (including the punctuation and element separators).

so it has to be 256

**Comment by Oroton** [comment]
I think the maximum length for a unique key. mysql is 1000bytes.. and from memory you multiply the values by 4.
so for two items it won't work if they are more than 125.. Once changed to 112 it worked fine for 
MyISAM.

Also. i didn't realise it was still set to 5.3 thank you.

Got this error on load though.

WebRPG

very long text

Warning: Cannot modify header information - headers already sent by (output started at /hermes/bosnaweb17a/b633/ipg.brcadmin/webrpg/source/account/login.php:23) in /hermes/bosnaweb17a/b633/ipg.brcadmin/webrpg/bootstrap.php on line 45 Warning: Cannot modify header information - headers already sent by (output started at /hermes/bosnaweb17a/b633/ipg.brcadmin/webrpg/source/account/login.php:23) in /hermes/bosnaweb17a/b633/ipg.brcadmin/webrpg/bootstrap.php on line 46 Something went wrong, got exception with message 'Unknown: open(/var/php_sessions/sess_2b1195b6323866a807f9384c903eb946, O_RDWR) failed: No such file or directory (2)'
Array
(
    [_GET] => Array
        (
        )

    [_POST] => Array
        (
        )

    [_COOKIE] => Array
        (
            [phpbb3_qvk69_u] => 48
            [phpbb3_qvk69_k] => aab424847f7ba60c
            [phpbb3_qvk69_sid] => cd20a1ad0a0b02c102d0bb9bfb7c0dc1
            [PHPSESSID] => 2b1195b6323866a807f9384c903eb946
        )

    [_FILES] => Array
        (
        )

    [_SESSION] => Array
        (
        )

    [_SERVER] => Array
        (
            [PATH] => /usr/local/bin:/usr/bin:/bin
            [SCRIPT_NAME] => /webrpg/public/index.php
            [REQUEST_METHOD] => GET
            [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
            [SCRIPT_FILENAME] => /home/users/web/b633/ipg.brcadmin/webrpg/public/index.php
            [REMOTE_PORT] => 46563
            [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
            [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.8
            [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
            [GATEWAY_INTERFACE] => CGI/1.1
            [SCRIPT_URL] => /webrpg/public/index.php
            [UNIQUE_ID] => WMke1AoUDEsAAIKc1NIAAAAL
            [SCRIPT_URI] => http://brissyriders.com/webrpg/public/index.php
            [SERVER_PORT] => 80
            [HTTP_COOKIE] => phpbb3_qvk69_u=48; phpbb3_qvk69_k=aab424847f7ba60c; phpbb3_qvk69_sid=cd20a1ad0a0b02c102d0bb9bfb7c0dc1; PHPSESSID=2b1195b6323866a807f9384c903eb946
            [SERVER_PROTOCOL] => HTTP/1.1
            [REQUEST_URI] => /webrpg/public/index.php
            [HTTP_HOST] => brissyriders.com
            [SERVER_SOFTWARE] => Apache/2
            [DOCUMENT_ROOT] => /home/users/web/b633/ipg.brcadmin
            [SERVER_NAME] => brissyriders.com
            [SERVER_ADMIN] => cgiadmin@yourhostingaccount.com
            [HTTP_ACCEPT_ENCODING] => gzip
            [HTTP_CONNECTION] => keep-alive
            [REMOTE_ADDR] => 101.165.72.195
            [TZ] => EST5EDT
            [PHP_SELF] => /webrpg/public/index.php
            [REQUEST_TIME_FLOAT] => 1489575637.0506
            [REQUEST_TIME] => 1489575637
            [argv] => Array
                (
                )

**Comment by BlackScorp** [comment]
Unknown: open(/var/php_sessions/sess_2b1195b6323866a807f9384c903eb946, O_RDWR) failed: No such file or directory (2) 

it seems like something is not correct with your session handling on your server. it seems like PHP Want to create a session file in /var/php_sessions but this folder not exists.

**Comment by BlackScorp** [comment]
also according to     [REQUEST_URI] => /webrpg/public/index.php  it seems like the public folder is not set as document root.

on your server create a subdomain , for example 

webrpg.brissyriders.com  and in the configuration for the subdomain use /webrpg/public/ as document root so if you open webrpg.brissyriders.com you can see only index.php and nothing else

**Comment by Oroton** [comment]
Why would it be requesting PHPBB3 array?

[_COOKIE] => Array
    (
        [phpbb3_qvk69_u] => 48
        [phpbb3_qvk69_k] => aab424847f7ba60c
        [phpbb3_qvk69_sid] => cd20a1ad0a0b02c102d0bb9bfb7c0dc1
        [PHPSESSID] => 2b1195b6323866a807f9384c903eb946
    )

**Comment by BlackScorp** [comment]
it does not, it is in your cookies for the domain  brissyriders.com . cookies are stored per domain on your local PC so you send them everytime you open the webpage. this is default workflow of cookies and has nothing to do with my script ;)

**Comment by BlackScorp** [comment]
VARCHAR (256) is the lenght in Text not in bytes. i need the error message you get for mysql. 

i think it is because of your hosting provider and the database interface

**Comment by Oroton** [comment]
the subdomain fixed some issues. I'm just looking into session handling

but the error message was
#1071 - Specified key was too long; max key length is 1000 bytes
