### ISSUE TITLE
No Login

### ISSUE THREAD

**Issue by Oroton** [BlackScorp/webrpg#4]
Successfully created user test with password test when clicking on Create User Dummy.

However nothing happens when I login with details.
U: test
P: test

**Comment by BlackScorp** [comment]
Cookies enabled?

**Comment by BlackScorp** [comment]
i see, your Server is really strange, i will programm a debugging output today so you can enable it it then and we will see

**Comment by BlackScorp** [comment]
@Oroton update the code ;)
