### ISSUE TITLE
On log in

### ISSUE THREAD

**Issue by Oroton** [BlackScorp/webrpg#5]
I hope you don't me posting the errors I get as i see them.

On login for test I get error in header

Something went wrong, got exception with message 'Undefined offset: 0'
Array
(
    [character] => 
    [characters] => Array
        (
        )

)

This is before character create.

**Comment by BlackScorp** [comment]
yeah will fix it later, this error occurs, because you dont have a character, the page should redirect to "newCharacter" if you dont have any

**Comment by BlackScorp** [comment]
i fixed the issue, please update the sourcecode and execute this SQL command https://github.com/BlackScorp/webrpg/blob/master/migrations/genderAndClass.sql
